#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Lab2_00292846.c
	gcc -std=c11 -o Lab2_00292846.exe Lab2_00292846.c
	
clean:
	rm Lab2_00292846.exe

