#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: lab7_00292846.c
	gcc -std=c11 -o Lab7_00292846.exe lab7_00292846.c
	
clean:
	rm Lab7_00292846.exe

