#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Lab9_00292846_Strings.c
	gcc -std=c11 -o Lab9_00292846.exe Lab9_00292846_Strings.c
	
clean:
	rm Lab9_00292846.exe

