#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: program1 program2 program3

program1: MakeFloats.c
	gcc -std=c11 -o MakeFloats.exe MakeFloats.c
program2: 
	gcc -std=c11 -o ReadFloats.exe ReadFloats.c
program3: 
	gcc -std=c11 -o changeVals.exe ChangeValues.c	
clean:
	rm MakeFloats.exe ReadFloats.exe





 