#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Lab10_00292846.c
	gcc -std=c11 -o Lab10_00292846.exe Lab10_00292846.c
	
clean:
	rm Lab10_00292846.exe

