#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Array_00292846.c
	gcc -std=c11 -o Array_00292846.exe Array_00292846.c
	
clean:
	rm Array_00292846.exe

