#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: lab6_00292846.c
	gcc -std=c11 -o Lab6_00292846.exe lab6_00292846.c
	
clean:
	rm Lab6_00292846.exe

