#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: polishCalculator.c
	gcc -std=c11 -o Project_2_00292846.exe polishCalculator.c
	
clean:
	rm Project_2_00292846.exe

