#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Project1_00292846.c
	gcc -std=c11 -o Project1_00292846.exe Project1_00292846.c
	
clean:
	rm Project1_00292846.exe

