#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: main

main: Lab8_00292846.c
	gcc -std=c11 -o Lab8_00292846.exe Lab8_00292846.c
	
clean:
	rm Lab8_00292846.exe

